### ISSUE TITLE
这个项目支持移动设备的播放吗？

### ISSUE THREAD

**Issue by Noahsarker** [JiaJiaJiang/SimpleDanmakuSite#1]
这里是一小段测试视频http://121.42.41.17/dm/player/?id=22，
在chrome下完美播放，F12中的手机端也可播放，但是真机测试页面空白无任何内容。
手头没有安卓设备，模拟器中也是无法加载。

**Comment by JiaJiaJiang** [comment]
我都还没做完呢你就开始用起来了。。。。我自己都还没部署上服务器测试过

**Comment by JiaJiaJiang** [comment]
另外移动设备上会调用触摸版的NyaP播放器，那个我还没做好。请再等等。

**Comment by Noahsarker** [comment]
额 当时没看到“开发中”。。。不好意思啦！不要方，慢慢搞！

**Comment by JiaJiaJiang** [comment]
你说的问题应该修好了，pull一下试试。我这里最新的chrome中测试是没问题的，在触摸版做好之前先用桌面版凑活一下用吧
