### ISSUE TITLE
关于在浏览器中播放错误

### ISSUE THREAD

**Issue by Ibuki-Suika** [JiaJiaJiang/SimpleDanmakuSite#2]
#已解决

自己在360浏览器（chrome内核模式）下可以播放（视频采用flv）
但是我让另一个人用他电脑的360浏览器（也是Chrome内核模式）就无法播放
（加载弹幕框架
创建播放器
获取视频地址
获取弹幕
弹幕已载入
加载视频
视频错误）
（和网络问题没关系，可以直接下载flv文件）

于是自己用firefox，以及Chrome访问，也是无法加载，
firefox控制台里提示（
load player NyaP es2016  inline-cloudflare-rocketloader-executed-1.js:18:1
Language:zh-CN  NyaP.es2016.min.js:1:58547
rendererMode: 1  NyaP.es2016.min.js:1:16187
Mod Inited:TextDanmaku  NyaP.es2016.min.js:1:5429
HTTP "Content-Type" 中的 "video/x-flv" 不支持。媒体资源加载失败。  player
error { target: <video#main_video>, isTrusted: true, currentTarget: <video#main_video>, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, composed: false, timeStamp: 2507.8491548603365, cancelBubble: false, originalTarget: <video#main_video> }  playPage.js:13:92
无法播放媒体。没有相应格式的解码器：video/x-flv  player
）

chrome://media-internals/ 信息：
（
render_id: 5
player_id: 0
frame_title: 麻枝准 x やなぎなぎ - 终わりの世界から
total_bytes: 20072549
streaming: false
single_origin: true
passed_cors_access_check: false
range_header_supported: true
pipeline_state: kStopped
error: FFmpegDemuxer: open context failed
pipeline_error: DEMUXER_ERROR_COULD_NOT_OPEN
）

log
（
Timestamp | Property | Value
-- | -- | --
00:00:00 00 | frame_title | 麻枝准 x やなぎなぎ - 终わりの世界から
00:00:00 752 | total_bytes | 20072549
00:00:00 752 | streaming | false
00:00:00 752 | single_origin | true
00:00:00 752 | passed_cors_access_check | false
00:00:00 752 | range_header_supported | true
00:00:00 775 | pipeline_state | kStarting
00:00:14 27 | error | FFmpegDemuxer: open context failed
00:00:14 28 | pipeline_error | DEMUXER_ERROR_COULD_NOT_OPEN
00:00:14 28 | pipeline_state | kStopping
00:00:14 28 | pipeline_state | kStopped
）
因该是解码器的原因，但是浏览器访问其他视频网站都没有任何问题。。。（比如B站）
目前能正常加载的只有我电脑上的360浏览器，这台电脑上的ie，firefox，chrome还有同学电脑上的360浏览器都不行。。。
请问您有什么解决办法吗?
谢谢 Orz

**Comment by JiaJiaJiang** [comment]
只支持浏览器本身支持的视频编码，没有引用第三方库来支持其它编码（比如flv）

**Comment by Ibuki-Suika** [comment]
谢谢
那为什么我这台电脑的360浏览器访问就行，而同学那边的就不行？

**Comment by Ibuki-Suika** [comment]
谢谢，刚刚重新转码了一下就行了（不要使用格式工厂不然保证只有音频23333）
感谢Orz

**Comment by JiaJiaJiang** [comment]
用格式工厂转码的时候注意视频编码要用h264，这是浏览器普遍支持的编码

**Comment by Ibuki-Suika** [comment]
谢谢~~~
